# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def extension_pods
  pod 'ATBaseExtensions', :git => 'https://github.com/ATiOSModule/ATBaseExtensions.git', :tag => '0.0.2'
end

target 'ATFaceDetectCamera' do
  
  use_frameworks!
  extension_pods

end

target 'ATFaceDetectCameraDemo' do
  
  use_frameworks!
  extension_pods
  
end
